### ISSUE TITLE
Make cygnus to accept NGSIv2 notifications

### ISSUE THREAD

**Issue by manucarrace** [telefonicaid/fiware-cygnus#1757] opened 2019-11-07 14:27 UTC

**Comment by fgalan** [comment] 2019-11-07 14:32
I think this issue is a duplicate of https://github.com/telefonicaid/fiware-cygnus/issues/953. I'd suggest to close it and focus discussion in the older (as it contasins more information and some implementation hints).

**Comment by AlvaroVega** [comment] 2019-11-08 06:53
https://github.com/telefonicaid/fiware-cygnus/issues/953 is currently in pinned issues :)

**Closed** 2019-11-08 12:22 UTC
Labels: backlog
