### ISSUE TITLE
[cygnus-ngsi][NGSIMongoDBSink] Fix error handling when collection already exists

### ISSUE THREAD

**Issue by thomaskoeck** [telefonicaid/fiware-cygnus#1377] opened 2017-01-15 17:17 UTC
Hi, 

I already posted this issue on Stackoverflow but I want to post it here too.

I want to save historical data into MongoDB using Fiware Cygnus. But whenever Cygnus receives a notification from Orion it wants to create a new collection instead of adding a document if the collection already exists. I get this error message from Cygnus:

`time=2017-01-14T20:58:11.785Z | lvl=WARN | corr=28eca6a8-da9c-11e6-841b-0242ac120009 | trans=9fa2d345-9aa1-4ff6-84df-75de5829a449 | srv=itg | subsrv=/building1 | comp=cygnus-ngsi | op=processNewBatches | msg=com.telefonica.iot.cygnus.sinks.NGSISink[590] : Command failed with error 48: 'a collection 'sth_itg.sth_/building1_TemperatureRoom1_room' already exists' on server iot-mongo:27017. The full response is { "ok" : 0.0, "errmsg" : "a collection 'sth_itg.sth_/building1_TemperatureRoom1_room' already exists", "code" : 48, "codeName" : "NamespaceExists" }`

This is my agent.conf file:

```
cygnus-ngsi.sources = http-source
cygnus-ngsi.sinks = mongo-sink
cygnus-ngsi.channels = mongo-channel

cygnus-ngsi.sources.http-source.type = org.apache.flume.source.http.HTTPSource
cygnus-ngsi.sources.http-source.channels = mongo-channel
cygnus-ngsi.sources.http-source.port = 5050
cygnus-ngsi.sources.http-source.handler = com.telefonica.iot.cygnus.handlers.NGSIRestHandler
cygnus-ngsi.sources.http-source.handler.notification_target = /notify
cygnus-ngsi.sources.http-source.handler.default_service = default
cygnus-ngsi.sources.http-source.handler.default_service_path = /
cygnus-ngsi.sources.http-source.interceptors = ts gi
cygnus-ngsi.sources.http-source.interceptors.ts.type = timestamp
cygnus-ngsi.sources.http-source.interceptors.gi.type = com.telefonica.iot.cygnus.interceptors.NGSIGroupingInterceptor$Builder
cygnus-ngsi.sources.http-source.interceptors.gi.grouping_rules_conf_file = /opt/apache-flume/conf/grouping_rules.conf


cygnus-ngsi.sinks.mongo-sink.type = com.telefonica.iot.cygnus.sinks.NGSIMongoSink
cygnus-ngsi.sinks.mongo-sink.channel = mongo-channel
#cygnus-ngsi.sinks.mongo-sink.enable_encoding = false
#cygnus-ngsi.sinks.mongo-sink.enable_grouping = false
#cygnus-ngsi.sinks.mongo-sink.enable_name_mappings = false
#cygnus-ngsi.sinks.mongo-sink.enable_lowercase = false
#cygnus-ngsi.sinks.mongo-sink.data_model = dm-by-entity
#cygnus-ngsi.sinks.mongo-sink.attr_persistence = row
cygnus-ngsi.sinks.mongo-sink.mongo_hosts = iot-mongo:27017
cygnus-ngsi.sinks.mongo-sink.mongo_username =
cygnus-ngsi.sinks.mongo-sink.mongo_password =
#cygnus-ngsi.sinks.mongo-sink.db_prefix = sth_
#cygnus-ngsi.sinks.mongo-sink.collection_prefix = sth_
#cygnus-ngsi.sinks.mongo-sink.batch_size = 1
#cygnus-ngsi.sinks.mongo-sink.batch_timeout = 30
#cygnus-ngsi.sinks.mongo-sink.batch_ttl = 10
#cygnus-ngsi.sinks.mongo-sink.data_expiration = 0
#cygnus-ngsi.sinks.mongo-sink.collections_size = 0
#cygnus-ngsi.sinks.mongo-sink.max_documents = 0
#cygnus-ngsi.sinks.mongo-sink.ignore_white_spaces = true

cygnus-ngsi.channels.mongo-channel.type = com.telefonica.iot.cygnus.channels.CygnusMemoryChannel
cygnus-ngsi.channels.mongo-channel.capacity = 1000
cygnus-ngsi.channels.mongo-channel.transactionCapacity = 100
```

I was able to make it work using MySQL, but I need a MongoDB because I want to retrieve the data with STH Comet later on.

Am I doing something wrong? Can someone help with this?

Thank you in advance.

Best regards,
Thomas

**Comment by frbattid** [comment] 2017-01-16 08:20
Hi @thomaskoeck !

Cygnus always try to create the collection upon notification reception, before inserting the data. Why? Because asking MongoDB for collection existence plus asking MongoDB for collection creation only when the collection does not exist are two operations through the driver; while asking MongoDB for always creating the collection is just one operation. Thus, if the collection exists, it should be OK if you see a DEBUG log trace telling you the collection exists. (*)

https://github.com/telefonicaid/fiware-cygnus/blob/master/cygnus-ngsi/src/main/java/com/telefonica/iot/cygnus/sinks/NGSIMongoSink.java#L364

```
try {
   backend.createDatabase(dbName);
   backend.createCollection(dbName, collectionName, collectionsSize, maxDocuments, dataExpiration);
   backend.insertContextDataRaw(dbName, collectionName, aggregation);
} catch (Exception e) {
   throw new CygnusPersistenceError("-, " + e.getMessage());
} // try catch
```

The problem is you are experiencing a WARN log trace, which is bad. What version of MongoDB are you using? Reviewing the code, it could be a problem when interpreting MongoDB responses upon collection creation, which is not based in the error code but in the message string: if you MongoDB returns a different message than expected, an error is raised. This is must be improved, for sure.

https://github.com/telefonicaid/fiware-cygnus/blob/master/cygnus-common/src/main/java/com/telefonica/iot/cygnus/backends/mongo/MongoBackendImpl.java#L106

```
// create the collection
try {
   db.createCollection(collectionName);
} catch (Exception e) {
   if (e.getMessage().contains("collection already exists")) {
      LOGGER.debug("Collection already exists, nothing to create");
   } else {
      throw e;
   } // if else
} // try catch
```

(*) This could be improved by using a "cache" of already created databases and collections. Such a cache would save lot of operations through the MongoDB driver.  This idea has already been implemented for CKAN and MySQL sinks.

**Comment by thomaskoeck** [comment] 2017-01-16 09:21
Hi @frbattid,

thank you for your quick response. The problem simply is that there are no further documents inserted into the collection. When there does not yet exist a database and a collection, everything works perfectly fine. Cygnus receives a notification, it creates the database and the collection and inserts a document into it. But as soon as Cygnus receives a notification and the database already exists as well as a collection in it, I get the "error" message I mentioned above and no additional document is added to the collection. So no matter how many notifications Cygnus receives, there is always only one document in the collection in this database. In MySQL there is a new row added to the table for every received notification, so in the case of MongoDB I suppose there should be added a new document to the collection for every received notification. Or am I wrong with this?

Could you tell me what I might have done wrong?

I am using the latest Docker image of MongoDB as well as the latest Cygnus Docker image.

**Comment by frbattid** [comment] 2017-01-16 09:46
Yes, you 'are tight, @thomaskoeck , MySQL and MongoDB sinks conceptually work the same way. I.e. first time a notification is received, a database and a collection are created, and the data is inserted. Next notifications should be "appended" to already existent collections.

That's conceptually. The problem is in the implementation: in order to improve the performance, each time a notification is received, instead of asking for the existence of a database and a collection for the received data, the database and collections are <b>always</b> attempted for creation. As I tried to explain in my previous response, this is better than asking for the existence and then asking for creation. Please observe in the case the database and/or the collection already exist, Cygnus just notices about that, and a DEBUG trace is be logged before inserting the data. The problem is Cygnus does not notice about the database/table existence because the check is based on a hardcoded string instead of the error code. It seems such a string has changed from MongoDB versions.

In fact, the log Cygnus traces in your run says:

    'a collection 'sth_itg.sth_/building1_TemperatureRoom1_room' already exists'

While Cygnus expects to find the string:

    collection already exists

This is a bad a idea from our side, and must be replaced with a check regarding the error code.

**Comment by thomaskoeck** [comment] 2017-01-16 10:04
Ok, I see. So is there a way for me to fix this? Or could you update your Docker image at Dockerhub to fix this? Because I need to save the data to MongoDB because I want to retrieve this data later on using STH Comet and as far as I know Comet can only read from MongoDB. It is really urgent for me to have this functionality and to be able to save more than one document to the collection.

**Comment by frbattid** [comment] 2017-01-18 09:45
I'll try to have the fix before the end of sprint (end of January). In the meantime, you may try with MongoDB 3.2, which is the version we are using in production environments and is supposed to be working with Cygnus.

**Comment by thomaskoeck** [comment] 2017-01-18 16:48
Ok, thank you very much.

**Comment by frbattid** [comment] 2017-01-27 07:11
I've been able to reproduce the error. I can confirm the new error message is (MongoDB 3.4):

    Command failed with error 48: 'a collection 'sth_homes.sth_/home4_contador4_smartMeter' already exists' on server localhost:27017. The full response is { "ok" : 0.0, "errmsg" : "a collection 'sth_homes.sth_/home4_contador4_smartMeter' already exists", "code" : 48, "codeName" : "NamespaceExists" }

While old error message was (MongoDB 3.2):

    Command failed with error 48: 'collection already exists' on server qa-orion-be-01:27017. The full response is { "ok" : 0.0, "errmsg" : "collection already exists", "code" : 48 }

In any case, the Java API only provides a string; no object where I can get a code error or soemthing similar. I mean, I already have to parse the string looking for some "common" pattern. In this case I guees it will be `"code" : 48`... Until it changes again! :)

**Comment by frbattid** [comment] 2017-01-27 09:42
Fixed in PR https://github.com/telefonicaid/fiware-cygnus/pull/1388

**Closed by frbattid** 2017-01-27 09:42 UTC
Labels: bug
