### ISSUE TITLE
CKAN 2.4 does not return by default the package details on organization show

### ISSUE THREAD

**Issue by acs** [telefonicaid/fiware-cygnus#546] opened 2015-09-29 05:51 UTC
Hi!

We have been using Cygnus CKAN for publishing data in demo.ckan.org for some months. But with the last update in demo.ckan.org (we need to change some code using CKAN API to adapt to it), the creation of entities inside a dataset is not working anymore. 

The config we are using for the CKAN sink is:

```
# OrionCKANSink configuration: org1
cygnusagent.sinks.ckan-sink-org1.channel = ckan-channel-org1
cygnusagent.sinks.ckan-sink-org1.type = com.telefonica.iot.cygnus.sinks.OrionCKANSink
cygnusagent.sinks.ckan-sink-org1.api_key = XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
cygnusagent.sinks.ckan-sink-org1.ckan_host = demo.ckan.org
cygnusagent.sinks.ckan-sink-org1.ckan_port = 80
# cygnusagent.sinks.ckan-sink-org1.default_dataset = room
cygnusagent.sinks.ckan-sink-org1.orion_url = http://localhost:1026
cygnusagent.sinks.ckan-sink-org1.attr_persistence = row
cygnusagent.sinks.ckan-sink-org1.ssl = false
```

We have tested it with Cygnus 0.8.2. The message received in CKAN Cygnus sink is:

```
cygnus_1      | 2015-09-28 17:19:04,533 (SinkRunner-PollingRunner-DefaultSinkProcessor) [INFO - com.telefonica.iot.cygnus.sinks.OrionCKANSink.persist(OrionCKANSink.java:198)] [ckan-sink-org1] Persisting data at OrionCKANSink (orgName=orga_a, pkgName=orga_a_room, resName=manual_retest_orga_a, data=1443460744518, 2015-09-28T17:19:04.518Z, temperature, centigrade, "-", [])
```

"org_a" and "orga_a_room" are created correctly if they don't exist.

The error we receive is:

If the organization does not exists, it is created and the dataset and the error is:

```
cygnus_1      | 2015-09-28 17:56:48,288 (SinkRunner-PollingRunner-DefaultSinkProcessor) [ERROR - com.telefonica.iot.cygnus.sinks.OrionSink.process(OrionSink.java:178)] 
Runtime error (Don't know how to treat the response code. 
Possibly the resource already exists (respCode=503, resourceName=manual_temp1_orga_a))
```

If the organization and dataset already exists the error is:

```
cygnus_1      | 2015-09-28 17:36:53,429 (SinkRunner-PollingRunner-DefaultSinkProcessor) [ERROR - com.telefonica.iot.cygnus.sinks.OrionSink.process(OrionSink.java:178)] 
Runtime error (Don't know how to treat the response code. 
Possibly the resource already exists (respCode=404, resourceName=manual_r44_orga_a))
```

How we can proceed to debug this issue?

Cheers

**Comment by frbattid** [comment] 2015-09-29 06:17
Hi @acs, many thanks for the feedback. Before deciding how to proceed, I need to know where can I found the details about those changes in the CKAN API. Are the changes related to a new version of the API? Which version is currently `demo.ckan.org` running? Which was the previous one?

**Comment by acs** [comment] 2015-09-29 07:51
Hi Francisco!

Those changes to work with the new API are in our code (we read CKAN contents to show them in a browser), not in Cygnus CKAN. I am sorry about the noise.

We are using Cygnus CKAN without any changes and configure to publish in demo.ckan.org. I have tested 0.8.2 and develop branches, and both have the same issues.

Thanks for the quick response!

**Comment by frbattid** [comment] 2015-09-29 10:14
`demo.ckan.org` is currently using the 2.4 version of the API, while Cygnus was designed for 2.2. There must be a change in the API avoiding backward compatibility. Still researching for it.

**Comment by frbattid** [comment] 2015-09-29 11:11
Found! The problem is 2.2 version <b>always</b> returned the packages within an organization when showing the details of such an organization. Nevertheless, now 2.4 version only returns the packages information if the `include_datasets` parameter is set to true... <b>by default, it is set to false</b>:

http://docs.ckan.org/en/ckan-2.4.0/api/#ckan.logic.action.get.organization_show

Cygnus expects this information about the packages is always shown, thus we have to fix it in order to set to true this parameter.

**Comment by acs** [comment] 2015-09-29 12:00
Great, exactly the same fix we need to do in our CKAN backend:

```
path: '/api/action/organization_show?id='+org_id+'&include_datasets=True',
```

Francisco I will be more than happy to test the fix once it is in develop branch (or master).

**Comment by frbattid** [comment] 2015-09-29 12:04
Well, I've assigned the issue to 0.9.0, which ends tomorrow :) Few time, but I'll try to have it. I accept the offer for testing the fix!

**Comment by acs** [comment] 2015-09-29 12:06
I will test it as real time as possible ;)

**Comment by frbattid** [comment] 2015-09-29 14:45
Update:

The `organization_show` now works by setting always `include_datasets=true` (2.2 contains such a parameter by defaulting to true, 2.4 defaults to false... why this change???).

The problem now is the `resource_create` method does not work. It is something related to the JSON dictionary causing an internal server error (500 status code returned). @acs, do you know the specific method invocation?

```
$ curl -X GET "http://demo.ckan.org:80/api/3/action/package_show?id=f2c4125b-27c8-4e07-94d7-d6d0c0b65154" | python -m json.tool
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  1228  100  1228    0     0   1384      0 --:--:-- --:--:-- --:--:--  1386
{
    "help": "http://demo.ckan.org/api/3/action/help_show?name=package_show",
    "result": {
        "author": null,
        "author_email": null,
        "creator_user_id": "b0a12b23-4cee-4d8c-993e-723421a0a296",
        "extras": [],
        "groups": [],
        "id": "f2c4125b-27c8-4e07-94d7-d6d0c0b65154",
        "isopen": false,
        "license_id": null,
        "license_title": null,
        "maintainer": null,
        "maintainer_email": null,
        "metadata_created": "2015-09-29T14:09:21.629953",
        "metadata_modified": "2015-09-29T14:09:21.669256",
        "name": "frb_org_test1_frb_pkg_test2",
        "notes": null,
        "num_resources": 0,
        "num_tags": 0,
        "organization": {
            "approval_status": "approved",
            "created": "2015-09-29T10:55:53.479724",
            "description": "",
            "id": "402f83c1-0070-4694-a1d9-f25b1d114631",
            "image_url": "",
            "is_organization": true,
            "name": "frb_org_test1",
            "revision_id": "26993878-9024-429a-b753-cc087b0ce382",
            "state": "active",
            "title": "",
            "type": "organization"
        },
        "owner_org": "402f83c1-0070-4694-a1d9-f25b1d114631",
        "private": false,
        "relationships_as_object": [],
        "relationships_as_subject": [],
        "resources": [],
        "revision_id": "47acfd70-8d26-4ebb-8cbd-6cababc627b1",
        "state": "active",
        "tags": [],
        "title": "frb_org_test1_frb_pkg_test2",
        "type": "dataset",
        "url": null,
        "version": null
    },
    "success": true
}
..
..
..
$ $ curl -X POST "http://demo.ckan.org:80/api/3/action/resource_create" -d '{ "name": "room1_room", "url": "none", "package_id": "f2c4125b-27c8-4e07-94d7-d6d0c0b65154" }' -H "Authorization: MY_API_KEY_IS_SECRET"
<!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN">
<html><head>
<title>500 Internal Server Error</title>
</head><body>
<h1>Internal Server Error</h1>
<p>The server encountered an internal error or
misconfiguration and was unable to complete
your request.</p>
<p>Please contact the server administrator,
 [no address given] and inform them of the time the error occurred,
and anything you might have done that may have
caused the error.</p>
<p>More information about this error may be available
in the server error log.</p>
<hr>
<address>Apache/2.2.22 (Ubuntu) Server at demo.ckan.org Port 80</address>
</body></html>

**Comment by acs** [comment] 2015-09-29 19:52
No, until now we have been created CKAN resources always using Cygnus CKAN backend. I will play a bit and if I find something, I will feedback here!

**Comment by acs** [comment] 2015-09-29 20:14
I have confirmed the problem. Maybe we should ask in:

https://lists.okfn.org/mailman/listinfo/ckan-dev

or directly to demo.ckan.org sysadmins.

Have you checked against other CKAN instance? Maybe the one in FIWARE Labs?

Cheers

**Comment by frbattid** [comment] 2015-09-30 07:17
Against the one in FIWARE Lab works because it is based on CKAN 2.2. This is as problem with the 2.4 API. I'll ask the administrators / generate an issue on CKAN. Thanks!

**Comment by frbattid** [comment] 2015-09-30 07:38
http://stackoverflow.com/questions/32860432/not-able-to-create-a-resource-in-demo-ckan-org-through-the-api-500-error

@acs, please upvote it in order it gains relevance.

**Comment by frbattid** [comment] 2015-10-01 06:46
This is definitely a bug in CKAN API (2.4 version): https://github.com/ckan/ckan/issues/2665

The proposed workaround works and the resource can be created by adding an empty `format` field to the payload.

Nevertheless, another problem arises: http://stackoverflow.com/questions/32881002/no-view-created-for-a-resource-at-demo-ckan-org

**Comment by frbattid** [comment] 2015-10-02 07:44
Moving this to release/0.10.0, time for including it in 0.9.0 is gone.

**Comment by acs** [comment] 2015-10-02 07:56
Ok! Hmmm, it is a pity I don't have enough permissions in https://data.lab.fiware.org/ to create organizations, datastores and publish entities. Not sure if we will need to install our own CKAN portal. How are you working with CKAN Francisco?

I will monitor this ticket because we need to publish in open data the context for restaurants in the tour guide app.

**Comment by acs** [comment] 2015-10-22 16:20
https://github.com/ckan/ckan/issues/2665 is closed now and it works for me. So time to retest Cygnus 0.9! I will inform here about the progress.

**Comment by acs** [comment] 2015-10-22 17:01
With 0.9.0 it is not working. And trying to use "develop" it does not compile now:

```
[ERROR] Failed to execute goal on project cygnus: Could not resolve dependencies for project com.telefonica.iot:cygnus:jar:0.9.0_SNAPSHOT: Could not find artifact org.apache.hadoop:hadoop-core:jar:0.20.2-cdh3u6 in central (https://repo.maven.apache.org/maven2) -> [Help 1]
```

**Comment by hermanjunge** [comment] 2015-10-27 22:00
+1 I had to implement

    sed -i pom.xml -e "s/0.20.2-cdh3u6/1.2.1/g" 

To be able to compile the code of the current `develop` branch (`3366184c50620e068a4fe02840b74c86b7cef55a`).

**Comment by frbattid** [comment] 2015-10-28 07:27
It is correct, Cygnus 0.10.0 will need to match the exactly hadoop-core version. There is an [open issue](https://github.com/telefonicaid/fiware-cygnus/issues/559) regarding that; better discuss it there if needed.

**Comment by frbattid** [comment] 2015-10-30 10:17
Implemented in PR https://github.com/telefonicaid/fiware-cygnus/pull/585

@acs, please, test it.

**Closed** 2015-10-30 12:42 UTC
Labels: bug, P1

**Comment by acs** [comment] 2015-11-02 07:10
I have been testing with more deep this fix and it creates correctly datasets and the entities, but it is failing to add new values to an already existing entity. The logs I can see in Cygnus are:

```
cygnus_1      | 2015-11-02 07:04:40,316 (SinkRunner-PollingRunner-DefaultSinkProcessor) [INFO - com.telefonica.iot.cygnus.sinks.OrionCKANSink.persistOne(OrionCKANSink.java:207)] [ckan-sink-org1] Persisting data at OrionCKANSink (orgName=organiz_a, pkgName=organiz_a_room, resName=manual_rrdev2_orga_a_organiz_a, data=1446447878816,2015-11-02T07:04:38.816Z,manual_rrdev2_orga_a,organiz_a,temperature,centigrade,"20",[])
```

which seems to be correct for:

http://demo.ckan.org/dataset/organiz_a_room/resource/a019689e-6fa4-478d-87eb-14fe7f779fee

but no new value appears in this entity.

**Comment by frbattid** [comment] 2015-11-02 07:45
This is a totaly different issue: https://github.com/telefonicaid/fiware-cygnus/issues/589
